#!/bin/sh

containers=$(<scripts/containers_list)
echo ---------------------------------------------------------------
echo containers list is $containers
echo ---------------------------------------------------------------

docker_ssh()
{
  (cd scripts && ./guest_ssh.sh)
}

docker_stop()
{
   (cd scripts && ./down)
}

docker_start()
{
   (cd scripts && ./up)
}

docker_rebuild()
{
  (cd scripts && ./rebuild)
}

docker_setip()
{
   (cd scripts && ./guest_set_host_ip.sh)
}

docker_restartapp()
{
   (cd scripts && ./restart_app)
}

# We only care about the 1 argument that is passed.
case $1 in
    ssh|SSH)
        docker_ssh
        ;;
    stop|STOP)
        docker_stop
        ;;
    restart|RESTART)
        docker_stop
        docker_start
        ;;
    start|START)
        docker_start
        ;;
    rebuild|REBUILD)
        docker_rebuild
        ;;
    setip|SETIP)
        docker_setip
        ;;
    restartapp|RESTARTAPP)
        docker_restartapp
        ;;
    *)
        echo "Docker [STOP | START | RESTART | SSH | REBUILD | SETIP | RESTARTAPP]"
        echo "Usage:"
        echo "  ./dock stop|start|restart|ssh|rebuild|setip|restartapp"
esac

exit 1
